version: '3.8'

services:
  app:
    build: .
    container_name: nest_app
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      - db
    env_file: .env
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
